### ISSUE TITLE
Link Quebrado

### ISSUE THREAD

**Issue by fernandogomesfg** [HercoZauZau/Kutiva#5]
Gostaria de relatar um problema encontrado no repositório de dados públicos da Kutiva referente ao link **Indicadores Económico-Financeiro das Empresas (IEFE)** na seção de **Economia e Finanças**. Ao tentar acessar esse link específico, encontrei uma mensagem indicando que não existem documentos ou arquivos de mídia na pasta correspondente aos dados de Moçambique.

**Comment by HercoZauZau** [comment]
Resolvido. Obrigado.
